name: Deploy to ECR and ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: |
          docker build -t clinicfiapproject .
          docker tag clinicfiapproject:latest public.ecr.aws/e9h5j2l3/clinicfiapproject:latest

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/e9h5j2l3

      - name: Push image to Amazon ECR
        run: |
          docker push public.ecr.aws/e9h5j2l3/clinicfiapproject:latest

      - name: Update ECS service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecs update-service --cluster clinicfiapproject --service clinicfiapproject-service --force-new-deployment
